### ISSUE TITLE
DLM comments meta issue

### ISSUE THREAD

**Issue by slochower** [slochower/smirnoff-host-guest-manuscript#25]
Will keep updating this issue...

This will be closed by #26.

## Abstract

- [x] Add error bars to numbers in the abstract
- [x] Typos
   Updated in 1f4e6f5

## Introduction
- [x] It's not super clear to me why the bromodomain example (and reversible work calculations in particular) are singled out here. You probably need a transition sentence between your general "calculations of binding thermodynamics are hard" first couple sentences and this concrete example.
- [x] Also, what does this example have to do with the sentence after it?
   Attempted in 1003289
- [x] Parameters should be written as "lines of parameters"
   I actually think for GAFF 1.7 this is close to true, although one could argue that each dihedral "line" contains information about `k`, `per`, and `phase`.
- [x] "Does about as well as"
   Addressed in 35a20ba

## Methods

- [x] Adjust phrasing around Henriksen et al.
   Addressed in 73b10d8
- [x] Familiarize ParmEd
   Expanded in 6b9f87e
- [x] Clarify that HMR does scale by 3.
   Commented in c5b196d
- [x] Clarify how dummy atoms help alignment
   See 005183a
- [x] Look up long-range dispersion correction info
   Controlled by `vdwmeth` and `vdw_correction`.
   Note: http://archive.ambermd.org/201803/0090.html
   Updated in 005183a
- [x] Rephrase "restraint coordinate uncertainty"
- [x] Clarify why we didn't use `scale_w`.
   Wrote in 4160ef6
   Turns out GAFF v2.1 endpoints were only run to 500 ns instead of the expected 1 us. Yipes. Running those longer now and then will recalculate all quantities & update graphs.
- [x] Clarify the bootstrapping integration of 100,000 curves.
   Expanded in 6e25add.

## Results
- [x] Error bars on RMSEs
   Updated table in 53e109c. Need to fix headers still.
- [x] Comment on why GAFF 2 is "more different"
   Split sections, added a few sentences on differences due to stiffness.  1d1172a
- [x] Clarify Figure 5 caption phrasing
- [x] Define gray circles in Figure 6.
   Updated in 902a4b2.
- [x] Error bars in text after Figure 6.
- [x] Mention GAFF v1.7 hydroxyl LJ parameters are set to 0
   Added more information and citations in 1818965.
- [x] Which torsions are specified in the Dihedral parameters subsection
- [x] Clarify "only height differences"
- [x] Expand on rigidity figure
- [x] Expand on the consequences of GAFF v2.1 differences (make a judgment call)

## Typos
- [x] Typeset host-guest complexes differently
- [x] Eliminate future tense

## Discusion
> So… maybe you'll get to it here but it seems like we need more of a "so what"? somewhere in the paper. These are great calculaitions, the data is great and compelling, but… Do we need more experimental data (and of what kind) to be able to tell which force fields are better and by how much? Are there clear areas for improvement? What should the next study in this direction look at?

> Also, I'd love to see a bit of contact made between these results and the known challenges facing alpha-CD and beta-CD modeling, e.g. as addressed in the "benchmarksets" paper I wrote wth Mike. Are sampling issues all resolved, etc.?

> Seems like you are missing an Acknowledgments section somewhere prior to this one.
