### ISSUE TITLE
JDC comments meta issue

### ISSUE THREAD

**Issue by slochower** [slochower/smirnoff-host-guest-manuscript#29]
# Title
- [x] Add FF version
- [x] Group → Initiative
   Fixed in ded9b3c.

# Abstract
- [x] Typos & wording
- [x] Be specific about versions
- [x] Add charge and solvent models

# Introduction
- [x] Add more about motivation
   > I think this manuscript jumps into the what way before you even explain why you are doing this. What is the value of comparing with host-guest data? Why are host-guest complexes good model systems? What challenges do they isolate? Why are they experimentally tractable? What do we learn from comparing binding free energies? From comparing enthalpies and entropies? Do we have reason to believe the accuracies on host-guest systems tell us something about accuracies on protein-ligand systems, or modes of failure? What can we do with this information once you've computed it?
    > You've done lots of fantastic work in the past laying the answers to all of these questions out. A clear, well-referenced line of reasoning through all of those questions to justify why you are doing all of this belongs in the Introduction, and should appear before you get to the what you are doing.
    > Just to give a more concrete example: I'm fond of the first few paragraphs of the Introduction to the SAMPL6 host-guest manuscript which explains why host-guest systems are so valuable: https://www.biorxiv.org/content/biorxiv/early/2018/09/25/371724.full.pdf
- [ ] Update date
- [x] Mention that the parameters were not yet optimized
- [x] Further refine the "does about as well as" claim

# Methods
- [ ] Link to CSV of Table 1
- [x] Split charge into its own column
- [x] Add SI figure showing that AM1-BCC charges don't change if the entire cyclodextrin is used
- [x] Did we really use different versions of `pmemd.cuda`? 
   Yes, and I agree it wasn't necessary but we used the latest version available when doing each set of simulations.
- [x] Add more about blocking analysis
- [x] Typos
- [x] Specify that "mean" is the sample mean, not the bootstrap mean. (Well, double check)

# Results
- [x] Describe connection between conformational preferences and binding free energies
- [x] See if there is a way to put the colors in the key
- [x] Further figure 4 by cyclodextrin and then functional group 
- [x] Typo
- [x] Put version number in section header
- [ ] Specify starting structure for RMSD calculation and absence of restraints.

# Discussion
> Do you have a good idea about how sensitive the binding thermodynamics are to perturbations in different classes of parameters? Could you assess this via post-simulation analysis?

**Comment by slochower** [comment]
Done.
